# Generated by Django 6.0.8 on 2026-09-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0015_alter_testhistory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="suitehistory",
            name="average_teardown_duration",
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suitehistory",
            name="average_tests_duration",
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
