# Generated by Django 6.0.8 on 2026-09-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0069_result_browser"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="average_teardown_duration",
            field=models.FloatField(
                default=-1,
                editable=False,
                help_text="Seconds of teardown duration from recent runs on default branches",
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="average_tests_duration",
            field=models.FloatField(
                default=-1,
                editable=False,
                help_text="Seconds of tests duration from recent runs on default branches",
            ),
        ),
    ]
