# Generated by Django 6.0.8 on 2026-09-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_oidc_identity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="email_domain",
            field=models.CharField(
                blank=True,
                help_text="Company domain (example.com) or a single address (you@gmail.com)",
                max_length=100,
                verbose_name="Email domain or address",
            ),
        ),
    ]
