from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path(
        "",
        views.IndexView.as_view(),
        name="index",
    ),
    path(
        "<path:path>/tests/disabled/regex",
        views.DisabledTestsRegexView.as_view(),
        name="disabled-tests-regex",
    ),
    path(
        "<path:path>/tests/disabled",
        views.DisabledTestsView.as_view(),
        name="disabled-tests",
    ),
    path(
        "<path:path>/tests/<int:test_id>/export.json",
        views.TestDownloadView.as_view(),
        name="test-export",
    ),
    path(
        "<path:path>/tests/<int:test_id>/export",
        views.TestRawView.as_view(),
        name="test-export-page",
    ),
    path(
        "<path:path>/tests/<int:test_id>",
        views.TestResultsView.as_view(),
        name="test-results",
    ),
    path(
        "<path:path>/tests/<int:test_id>/results/<int:result_id>/export.md",
        views.ResultDownloadView.as_view(),
        name="result-export",
    ),
    path(
        "<path:path>/tests/<int:test_id>/results/<int:result_id>/export",
        views.ResultRawView.as_view(),
        name="result-export-page",
    ),
    path(
        "<path:path>/tests/<int:test_id>/results/<int:result_id>",
        views.TestResultView.as_view(),
        name="test-result",
    ),
    path(
        "_result-details/<int:result_id>",
        views.ResultDetailsView.as_view(),
        name="result-details",
    ),
    path(
        "<path:path>/results",
        views.ResultsView.as_view(),
        name="results",
    ),
    path(
        "<path:path>/results/suite/<int:suite_id>",
        views.ResultsView.as_view(),
        name="suite-results",
    ),
    path(
        "<path:path>/results/regex",
        views.ResultsRegexView.as_view(),
        name="results-regex",
    ),
    path(
        "<path:path>/metrics/export.json",
        views.MetricsDownloadView.as_view(),
        name="metrics-export",
    ),
    path(
        "<path:path>/metrics/export",
        views.MetricsRawView.as_view(),
        name="metrics-export-page",
    ),
    path(
        "<path:path>/metrics/tests/<int:test_id>/maintainer",
        views.TestMaintainerView.as_view(),
        name="test-maintainer",
    ),
    path(
        "<path:path>/metrics",
        views.MetricsView.as_view(),
        name="metrics",
    ),
    path(
        "<path:path>/suite/<int:suite_id>",
        views.TestsView.as_view(),
        name="suite-tests",
    ),
    path(
        "<path:path>",
        views.TestsView.as_view(),
        name="tests",
    ),
]
